// Generated by CoffeeScript 1.4.0
(function() {
  var Cider, Clock, Entity, Game, GameController, Level,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    _this = this;

  Clock = (function() {

    Clock.prototype.maxStep = 50;

    Clock.prototype.timeScale = 1;

    function Clock(target) {
      this.target = target != null ? target : 0;
      this.delta = __bind(this.delta, this);

      this.tick = __bind(this.tick, this);

      this.reset = __bind(this.reset, this);

      this.set = __bind(this.set, this);

      this.base = c.Clock.time;
      this.last = c.Clock.time;
    }

    Clock.prototype.set = function(target) {
      this.target = target || 0;
      return this.base = c.Clock.time;
    };

    Clock.prototype.reset = function() {
      return this.base = c.Clock.time;
    };

    Clock.prototype.tick = function() {
      var delta;
      delta = c.Clock.time - this.last;
      this.last = c.Clock.time;
      return delta;
    };

    Clock.prototype.delta = function() {
      return c.Clock.time - this.base - this.target;
    };

    return Clock;

  })();

  Clock.maxStep = 50;

  Clock.timeScale = 1;

  Clock.time = 0;

  Clock._last = 0;

  Clock.step = function() {
    var current, delta;
    current = Date.now();
    delta = current - c.Clock._last;
    c.Clock.time += Math.min(delta, c.Clock.maxStep) * c.Clock.timeScale;
    return c.Clock._last = current;
  };

  /* --------------------------------------------
       Begin level.coffee
  --------------------------------------------
  */


  Level = (function() {

    function Level(game, options) {
      this.game = game;
      if (options == null) {
        options = {};
      }
      this.setPxSize = __bind(this.setPxSize, this);

      this.size = {
        x: 100,
        y: 50
      };
      this.tileSize = 16;
      c.extend(this, options);
      this.setPxSize();
    }

    Level.prototype.setPxSize = function() {
      return this.pxSize = {
        x: this.size.x * this.tileSize,
        y: this.size.y * this.tileSize
      };
    };

    return Level;

  })();

  /* --------------------------------------------
       Begin gamecontroller.coffee
  --------------------------------------------
  */


  GameController = (function() {

    function GameController() {
      this.holding = __bind(this.holding, this);

      this.triggered = __bind(this.triggered, this);

      this._keyup = __bind(this._keyup, this);

      this._keydown = __bind(this._keydown, this);

      this.update = __bind(this.update, this);
      this._triggered = [];
      this._holding = [];
    }

    GameController.prototype.update = function() {
      return this._triggered = [];
    };

    GameController.prototype._keydown = function(e) {};

    GameController.prototype._keyup = function(e) {};

    GameController.prototype.triggered = function(action) {};

    GameController.prototype.holding = function(action) {};

    GameController.prototype._map = {
      'm1': -1,
      'm2': -3,
      'mup': -4,
      'mdown': -5,
      'backspace': 8,
      'tab': 9,
      'enter': 13,
      'pause': 19,
      'caps': 20,
      'esc': 27,
      'space': 32,
      'page up': 33,
      'page down': 34,
      'end': 35,
      'home': 36,
      'left': 37,
      'up': 38,
      'right': 39,
      'down': 40,
      'insert': 45,
      'delete': 46,
      '_0': 48,
      '_1': 49,
      '_2': 50,
      '_3': 51,
      '_4': 52,
      '_5': 53,
      '_6': 54,
      '_7': 55,
      '_8': 56,
      '_9': 57,
      'a': 65,
      'b': 66,
      'c': 67,
      'd': 68,
      'e': 69,
      'f': 70,
      'g': 71,
      'h': 72,
      'i': 73,
      'j': 74,
      'k': 75,
      'l': 76,
      'm': 77,
      'n': 78,
      'o': 79,
      'p': 80,
      'q': 81,
      'r': 82,
      's': 83,
      't': 84,
      'u': 85,
      'v': 86,
      'w': 87,
      'x': 88,
      'y': 89,
      'z': 90,
      'num 0': 96,
      'numpad 1': 97,
      'numpad 2': 98,
      'numpad 3': 99,
      'numpad 4': 100,
      'numpad 5': 101,
      'numpad 6': 102,
      'numpad 7': 103,
      'numpad 8': 104,
      'numpad 9': 105,
      'multiply': 106,
      'add': 107,
      'subtract': 109,
      'decimal': 110,
      'divide': 111,
      'f1': 112,
      'f2': 113,
      'f3': 114,
      'f4': 115,
      'f5': 116,
      'f6': 117,
      'f7': 118,
      'f8': 119,
      'f9': 120,
      'f10': 121,
      'f11': 122,
      'f12': 123,
      'shift': 16,
      'ctrl': 17,
      'alt': 18,
      'plus': 187,
      'comma': 188,
      'minus': 189,
      'period': 190
    };

    return GameController;

  })();

  /* --------------------------------------------
       Begin game.coffee
  --------------------------------------------
  */


  Game = (function() {

    function Game(options) {
      if (options == null) {
        options = {};
      }
      this.destroyEntity = __bind(this.destroyEntity, this);

      this.createEntity = __bind(this.createEntity, this);

      this.drawEntities = __bind(this.drawEntities, this);

      this.updateEntities = __bind(this.updateEntities, this);

      this.draw = __bind(this.draw, this);

      this.update = __bind(this.update, this);

      this.run = __bind(this.run, this);

      this.unpause = __bind(this.unpause, this);

      this.pause = __bind(this.pause, this);

      this.loadLevel = __bind(this.loadLevel, this);

      this.positionCamera = __bind(this.positionCamera, this);

      this.initializeElements = __bind(this.initializeElements, this);

      this.createElements = __bind(this.createElements, this);

      this.initializeDebugMode = __bind(this.initializeDebugMode, this);

      this._unique = 1;
      this.clock = new c.Clock;
      this.entities = [];
      this.resources = {};
      this.cSize = {
        x: 640,
        y: 320
      };
      this.tagName = 'div';
      this.className = '';
      this.id = 'cider-camera';
      this.gravity = 0;
      this.cPos = {
        x: 0,
        y: 0
      };
      this.debug = false;
      c.extend(this, options);
      this.createElements();
      this.initializeElements();
      if (this.debug) {
        this.initializeDebugMode();
        this.lastFrameStart = Date.now();
      }
      this.run();
    }

    Game.prototype.initializeDebugMode = function() {
      var style;
      this.debugEl = document.createElement('div');
      style = this.debugEl.style;
      this.debugEl.id = 'cider-debug';
      style.position = 'absolute';
      style.bottom = '0px';
      style.right = '0px';
      return document.body.appendChild(this.debugEl);
    };

    Game.prototype.createElements = function() {
      var cameraEl, el;
      cameraEl = document.createElement('div');
      cameraEl.id = this.id;
      cameraEl.className = this.className;
      this.cameraEl = cameraEl;
      el = document.createElement(this.tagName);
      el.id = 'cider-world';
      return this.el = el;
    };

    Game.prototype.initializeElements = function() {
      var cEs, es;
      cEs = this.cameraEl.style;
      cEs.width = "" + this.cSize.x + "px";
      cEs.height = "" + this.cSize.y + "px";
      cEs.overflow = 'hidden';
      cEs.position = 'relative';
      es = this.el.style;
      es.overflow = 'hidden';
      es.position = 'absolute';
      document.body.appendChild(this.cameraEl);
      return this.cameraEl.appendChild(this.el);
    };

    Game.prototype.positionCamera = function() {
      var es;
      es = this.el.style;
      es.left = "" + (-this.cPos.x) + "px";
      return es.top = "" + (-this.cPos.y) + "px";
    };

    Game.prototype.loadLevel = function(level) {
      var es;
      this.currentLevel = level;
      this.cPos = {
        x: 0,
        y: 0
      };
      es = this.el.style;
      es.width = "" + (level.size.x * level.tileSize) + "px";
      return es.height = "" + (level.size.y * level.tileSize) + "px";
    };

    Game.prototype.pause = function() {
      return this.paused = true;
    };

    Game.prototype.unpause = function() {
      return this.paused = false;
    };

    Game.prototype.run = function() {
      c.raf(this.run);
      c.Clock.step();
      this.tick = this.clock.tick();
      if (this.paused) {
        return;
      }
      if (this.debug) {
        this.fps = Math.round(1 / ((Date.now() - this.lastFrameStart) / 1000));
        this.lastFrameStart = Date.now();
      }
      this.positionCamera();
      this.update();
      this.draw();
      if (this.debug && ~~(Math.random() * 100) === 4) {
        return this.debugEl.innerText = "" + this.fps + " FPS";
      }
    };

    Game.prototype.update = function() {
      return this.updateEntities();
    };

    Game.prototype.draw = function() {
      return this.drawEntities();
    };

    Game.prototype.updateEntities = function() {
      var entity, _i, _len, _ref, _results;
      _ref = this.entities;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        entity = _ref[_i];
        _results.push(entity.update());
      }
      return _results;
    };

    Game.prototype.drawEntities = function() {
      var entity, _i, _len, _ref, _results;
      _ref = this.entities;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        entity = _ref[_i];
        _results.push(entity.draw());
      }
      return _results;
    };

    Game.prototype.createEntity = function(entity) {
      return this.entities.push(entity);
    };

    Game.prototype.destroyEntity = function(entity) {};

    return Game;

  })();

  /* --------------------------------------------
       Begin entity.coffee
  --------------------------------------------
  */


  Entity = (function() {

    function Entity(game, options) {
      this.game = game;
      if (options == null) {
        options = {};
      }
      this.setStyle = __bind(this.setStyle, this);

      this.draw = __bind(this.draw, this);

      this.update = __bind(this.update, this);

      this.drawElement = __bind(this.drawElement, this);

      this.initializeElement = __bind(this.initializeElement, this);

      this.createElement = __bind(this.createElement, this);

      this.game.createEntity(this);
      this.tagName = 'div';
      this.className = '';
      this.id = '';
      this.pos = {
        x: 0,
        y: 0
      };
      this.size = {
        x: 0,
        y: 0
      };
      c.extend(this, options);
      this.createElement();
      this.initializeElement();
    }

    Entity.prototype.createElement = function() {
      var el;
      el = document.createElement(this.tagName);
      el.className = this.className;
      el.id = this.id;
      return this.el = el;
    };

    Entity.prototype.initializeElement = function() {
      var es;
      es = this.el.style;
      es.position = 'absolute';
      es.background = '#f00';
      return this.game.el.appendChild(this.el);
    };

    Entity.prototype.drawElement = function() {
      var es;
      es = this.el.style;
      es.left = "" + this.pos.x + "px";
      es.top = "" + this.pos.y + "px";
      es.width = "" + this.size.x + "px";
      return es.height = "" + this.size.y + "px";
    };

    Entity.prototype.update = function() {};

    Entity.prototype.draw = function() {
      return this.drawElement();
    };

    Entity.prototype.setStyle = function(prop, val) {
      return this.el.style[prop] = val;
    };

    return Entity;

  })();

  /* --------------------------------------------
       Begin cider.coffee
  --------------------------------------------
  */


  Cider = {
    Game: Game,
    Entity: Entity,
    Clock: Clock,
    Level: Level,
    raf: (function() {
      var func;
      func = window.requestAnimationFrame || window.webkitRequestAnimationFrame || window.mozRequestAnimationFrame || window.oRequestAnimationFrame || window.msRequestAnimationFrame || function(callback) {
        return window.setTimeout(callback, 1000 / 60);
      };
      return function(cb, el) {
        return func.apply(window, [cb, el]);
      };
    })(),
    extend: function(dest) {
      var key, source, val, _i, _len, _ref;
      _ref = Array.prototype.slice.call(arguments, 1);
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        source = _ref[_i];
        for (key in source) {
          val = source[key];
          dest[key] = val;
        }
      }
      return dest;
    },
    log: function() {
      if (window.console) {
        return console.log(Array.prototype.slice.call(arguments));
      }
    }
  };

  window.c = window.Cider = Cider;

}).call(this);
